# Generated by Django 5.1.7 on 2025-03-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='patients/'),
        ),
    ]
